---
title: "Proyecto"

output: html_document
    
---
```{r message=FALSE}
library(dplyr)
library(tibble)
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(gganimate)
library(ggsci)
library(gifski)

```
## NUEVO
```{r message=FALSE}

datos <- read.csv(file="DATOS 1.csv",sep=";")

#Animada de fuerza laboral en cada pais 
pgg <- ggplot(
  datos,
  aes(Ao,FL,  color=Pas)) +   geom_line() +   scale_alpha() +
  labs(x = "Ao", y = "Fuerza laboral") +
  theme(legend.position = "top")
pgg+   
  geom_point(aes(group = seq_along(Ao))) +
  transition_reveal(Ao)

#Cada pa?s aparte
pgg <- ggplot(
  datos,
  aes(Ao,FL,  color=Pas)) +   geom_line() +   scale_alpha() +
  labs(x = "Ao", y = "Fuerza laboral") +
  theme(legend.position = "top")
pgg+   
  geom_point(aes(group = seq_along(Ao))) +
  facet_wrap(~Pas)+
  transition_reveal(Ao)


```



## Selección de datos 
```{r}
library(leaflet)
library(leaflet.extras)
library(magrittr)
library(plyr)
datos <- read.csv("fuerza laboral.csv")
mapa <- leaflet()%>% addTiles()%>%
  addMarkers(lng = datos$Longitud,lat = datos$latitud,
             clusterOptions = markerClusterOptions(),
             popup = paste("<b>País:", datos$Country.Name,"</b>", "<br/>",
                           "Fuerza laboral:", datos$Fuerzalaboral,"<br/>",
                           "Año:",datos$Year,"<br/>"
             )
  )

mapa%>%fitBounds(lng1 =--64.9912286 ,lat1 = -17.0568696,lng2 =-64.9912286 ,lat2 =-17.0568696 )

```

## Librerias

```{r message=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(gganimate)
library(ggsci)
library(gifski)
empleo_genero <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-10-16/empleo_genero.csv")
save(empleo_genero,file = "Empleo.Rdata")
load("Empleo.Rdata")
```

## Selección de datos 

```{r message=FALSE,comment=NA}
Datos <- empleo_genero %>%
  #Seleccion de las variables para cambiar a formato largo
  pivot_longer(-c(variable,codigo_pais_region,pais_region),
               names_to ="año",
               values_to = "porcentaje") %>% 
  #Renombrando el codigo del pais
 rename(codigo=codigo_pais_region) %>% 
  #Cambiando la variable año de caracter a numerico y codigo a factor
  mutate(año = as.numeric(año),
         codigo =as.factor(codigo) ) %>% 
  #Selecionando variable de interes "Desempleo"
  filter(variable == "desempleo_mujeres" |  variable == "desempleo_hombres") %>% 
  #Eliminando valores faltantes
  filter(!is.na(porcentaje)) %>% 
  #quitando la variable pais region
  select(-pais_region) %>%  
  #Filtrando paises en frontera con colobia
  filter(codigo == "COL" | codigo =="ECU" | codigo =="PER" | codigo =="VEN" | codigo =="BRA" | codigo =="PAN")
#Figura
gplot <- ggplot(Datos,aes(x=año,y=porcentaje,color=variable)) + 
  geom_line()+
  facet_wrap(~codigo,scales = "free")+
  scale_color_jco(name="Desempleo",
                  breaks = c("desempleo_hombres","desempleo_mujeres"),
                  labels=c("Hombres","Mujeres"))+
  theme_dark()+
  geom_tile(color="orange")+
  theme(text = element_text(size=10),
        legend.text = element_text( size = 12),
        legend.title = element_text(size=14),
        legend.position = "top",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = 'black'),
        legend.background = element_rect(fill = "white", color = NA),
        legend.key = element_rect(fill = "white"))+
  labs(x="Año",y="Porcentaje")+
  transition_reveal(año)

  progress <- interactive()
  if (progress) message('')
  
animate(gplot, renderer = gifski_renderer())

```

